text 1
GREAT JOB PAN LUMA...WE'LL TAKE IT FROM HERE

text 2
INCOMIMG MESSAGE FROM STRATUS CORPORATION

text 3
STRATUS COMMANDER LOCATED...INFORMING STRATUS

text 4
THANK YOU PAN LUMA...WE'RE SENDING IN A DROPSHIP

text 5
GOOD WORK...YOUR MISSION IS COMPLETE

text 6
LOCKED ON TO THE BEACON...PREPARE FOR LANDING

text 7
COMMANDER WOUNDED...MEDICAL DROPSHIP SUMMONED

text 8
COMMANDER RETURNING TO BASE...PREPARE FOR LANDING
