text 1
DROPSHIP BEACON SIGHTED...PREPARE FOR LANDING

text 2
EXCELLENT WORK...YOUR MISSION HAS BEEN COMPLETED

text 3
COMMANDER WOUNDED...MEDICAL DROPSHIP APPROACHING

text 4
COMMANDER RETURNING TO BASE...PREPARE FOR LANDING
