text 1
EXCELLENT WORK...YOUR MISSION IS COMPLETE

text 2
INCOMING MESSAGE FROM AEROGEN CORPORATION

text 3
GREETINGS PAN LUMA...GLAD TO HAVE WITH US

text 4
WE HAVE DISCOVERED A RICH PETRA-7 FIELD TO THE NORTH

text 5
COMMANDER WOUNDED...MEDICAL DROPSHIP SUMMONED

text 6
COMMANDER RETURNING TO BASE...PREPARE FOR LANDING
