text 1
SENSORS LOCKED TO THE BEACON...PREPARE FOR LANDING

text 2
MISSION COMPLETE...PREPARE FOR PICKUP, COMMANDER

text 3
BEACON REACTIVATED...SENDING IN REINFORCEMENTS

text 4
BEACON ACTIVATED...REINFORCEMENTS ARRIVING

text 5
DON'T FORGET TO INSPIRE YOUR TROOPS DURING BATTLE, COMMANDER

text 6
COMMANDER WOUNDED...THE MISSION IS OVER

text 7
THE MINING COLONY HAS BEEN DESTROYED...MISSION ABORTING
