text 1
DROPSHIP BEACON SIGHTED...PREPARE FOR LANDING

text 2
EXCELLENT WORK...THE ALIEN BASE HAS BEEN DESTROYED

text 3
COMMANDER WOUNDED...MEDICAL DROPSHIP SUMMONED

text 4
COMMANDER RETURNING TO BASE...PREPARE FOR LANDING

text 5
AEROGEN'S BASE HAS BEEN DESTROYED
