text 1
APPROACHING BASE...PREPARE FOR LANDING

text 2
PETRA-7 VENT ERUPTION DETECTED IN THE AREA

text 3
ALIEN THREAT ELIMINATED...PAN LUMA DROPSHIP APPROACHING

text 4
THE COMMANDER HAS ARRIVED SAFELY..GOOD WORK

text 5
COMMANDER WOUNDED...MEDICAL SHIP SUMMONED

text 6
COMMANDER RETURNING TO BASE...PREPARE FOR LANDING
