text 1
ARTIFACT FOUND...NOW LOCATE OUR P.O.W.S

text 2
ARTIFACT FOUND...GREAT WORK COMMANDER

text 3
P.O.W.S FREED...NOW FIND THAT ARTIFACT

text 4
P.O.W.S FREED...MISSION COMPLETE

text 5
COMMANDER CAPTURED BY THE ALIENS...THE MISSION IS OVER
