text 1
INCOMING MESSAGE FROM STRATUS

text 2
ALIENS LOCATED SOMEWHERE TO THE NORTH-WEST OF YOUR BASE

text 3
ALIEN BASE DESTROYED...GOOD WORK

text 4
COMMANDER RETURNING TO BATTLE...PREPARE FOR LANDING

text 5.
WARNING...WARNING...WARNING...

text 6
STRATUS IS ATTACKING OUR BASE

text 7
COMMANDER WOUNDED...MEDICAL DROPSHIP SUMMONED

text 8
DESTROY STRATUS...DEFEND YOUR BASE AT ALL COSTS

text 9
COMMANDER HAS BEEN ABDUCTED BY THE ALIENS!

text 10
STRATUS PLOT UNCOVERED...THEY'VE ALLIED WITH THE ALIENS...

text 11
...THEY'VE FOUND AN UNDERGROUND TEMPLE TO THE WEST...

text 12
...FIND AND SECURE IT

text 13
NEW VENT ERUPTION DETECTED NORTH OF YOUR BASE

text 14
UNDERGROUND ENTRANCE LOCATED...GOOD WORK

text 15
MISSION COMPLETE...WAIT FOR YOUR PICKUP COMMANDER

text 16
WARNING...DROPSHIP SIGNAL JAMMED...INCOMING SAUCER DETECTED
