text 1
BEACON SIGHTED...PREPARE FOR LANDING

text 2
CONGRATULATIONS...YOU HAVE DESTROYED THE ALIEN HIVE

text 3
ALIEN COUNCIL MEMBERS DETECTED ENTERING AREA

text 4
COMMANDER DOWN...MEDICAL DROPSHIP APPROACHING

text 5
COMMANDER HAS BEEN HEALED...APPROACHING BASE

text 6
ALIEN REINFORCEMENTS ENTERING AREA...THEY MUST BE STOPPED
