text 1
EXCELLENT WORK...YOU HAVE WON THE WAR

text 2
COMMANDER HAS BEEN WOUNDED...MEDICAL DROPSHIP APPROACHING

text 3
COMMANDER HEALED...PREPARE FOR LANDING

text 4
COMMANDER, WE ARE DROPPING OFF THE ESGAARD AT THE BASE
