text 2
ENERGY TANKS SENSED TO THE NORTH-WEST

text 4
YOU HAVE FOUND THE ENERGY WE SEEK

text 6
MIND LINK ESTABLISHED...PREPARE TO TELEPORT

text 8
MIND LINK ESTABLISHED...PREPARE TO TELEPORT

text 9
MIND LINK ESTABLISHED...TELEPORTING TO HIVE

text 10
STRATUS LEADER SENSED TO THE SOUTH OF THEIR BASE

text 12
STRATUS LEADER HAS ESCAPED

text 13
YOUR MISSION IS OVER, BROTHER

text 14
MIND PROBE REVEALS MORE ENERGY TANKS TO THE NORTH-WEST

text 18
YOU HAVE BEEN WOUNDED, BROTHER...PREPARE TO TELEPORT

text 19
YOU ARE RETURNING TO THE HIVE, BROTHER...PREPARE TO TELEPORT

text 20
THE HIVE HAS BEEN DESTROYED, BROTHER
