text 1
YOU HAVE WON...BE PROUD, BROTHER

text 2
YOU ARE RETURNING TO THE HIVE...PREPARE FOR TELEPORTATION

text 3
YOU HAVE DESTROYED THE ENEMY, BROTHER...

text 4
MESSAGE LINK BROKEN

text 5
THE STRATUS BASE HAS BEEN DESTROYED

text 6
...NOW, YOU MUST DESTROY STRATUS AS WELL, BROTHER

text 7
YOU HAVE BEEN MORTALLY WOUNDED...PREPARE TO TELEPORT
