text 1
YOU HAVE SUFFERED A MORTAL WOUND...PREPARE TO TELEPORT

text 2
STRATUS COMMANDER LOCATED...ABDUCTION SEQUENCE INITIATED

text 3
ABDUCTION SUCCESSFUL...BE PROUD, BROTHER

text 4
ROUTINE HUMAN ABDUCTION INITIATED

text 5
YOU ARE RETURNING TO THE HIVE...PREPARE FOR TELEPORTATION

text 6
MISSION COMPLETE...BE PROUD

text 7
MIND LINK ESTABLISHED...PREPARE FOR TELEPORTATION
