text 1
COMMANDER TICK HAS BEEN EXTERMINATED...BE PROUD

text 2
COMMANDER TICK HAS BETRAYED US...

text 3
DANGER...HOLD YOUR POSTITION...SCANNING AREA...

text 4
MIND LINK ESTABLISHED...PREPARE FOR LANDING

text 5
YOU HAVE BEEN MORTALLY WOUNDED...PREPARE TO TELEPORT

text 6
...HUNT TICK DOWN AND DESTROY HIM

text 7
ENEMY MINE FIELD DETECTED...TELEPORTING REINFORCEMENTS

text 8
TICK LOCATED...HIDING TO THE WEST AT AN UNDERGROUND ENTRANCE

text 9
SCANNING AREA FOR COMMANDER TICK...

text 10
...UNABLE TO ESTABLISH MIND CONTROL ON TICK...

text 11
PREPARE TO TELEPORT

text 12
WARNING...ENEMY MINE FIELD DETECTED TO THE WEST

text 13
NOW, FIND THE PETRA-7 TANKS, BROTHER

text 14
WE HAVE DETECTED AN ENEMY BASE TO THE NORTH-EAST

text 15
MIND LINK ESTABLISHED...PREPARE TO TELEPORT

text 16
MIND LINK ESTABLISHED...TELEPORTING YOU TO YOUR BASE, BROTHER

text 17
NOW BROTHER, ALL THE HUMANS MUST BE PUNISHED

text 18
YOU HAVE DONE WELL, BROTHER

text 19
BROTHER, USE YOUR WARRIORS TO TRIGGER THE MINE FIELD
