text 1
COMMANDER TICK AND HIS MEN ARE IN POSITION

text 2
COMMANDER TICK HAS BEGUN MOVEMENT

text 3
EXCELLENT WORK BROTHER...THE CITADEL IS NO MORE

text 5
MIND PROBE REVEALS ARTIFACT SITE HAS BEEN VACATED

text 6
MIND LINK ESTABLISHED...PREPARE FOR TELEPORTATION

text 7
YOU HAVE BEEN WOUNDED, BROTHER...PREPARE TO TELEPORT

text 8
MIND LINK ESTABLISHED...REINFORCEMENTS TELEPORTING TO BASE

text 11
MIND LINK ESTABLISHED, BROTHER...PREPARE FOR TELEPORTATION

text 12
LUNATEKS CAPTURED...TEST ONE ON THE HUMANS TO THE EAST
