text 1
DROPSHIP BEACON SIGHTED...PREPARE FOR DROP-OFF

text 2
COMMANDER WOUNDED...MEDICAL DROPSHIP APPROACHING

text 3
COMMANDER HEALED...RETURNING TO BASE

text 4
MISSION COMPLETE...GREAT WORK COMMANDER

text 5
WARNING...WARNING...WARNING...BASE DESTROYED

text 6
INTELLIGENCE REPORTS STRATUS BETRAYAL

text 7
TAKE THEM OUT COMMANDER...DESTROY STRATUS

text 8
STRATUS DESTROYED...TAKE OUT THE ALIENS COMMANDER
