text 1
PREPARE YOUR TROOPS COMMANDER

text 2
THE STRATUS BASE HAS BEEN DESTROYED

text 3
YOUR BASE HAS BEEN DESTROYED

text 4
MISSION COMPLETE...GREAT WORK COMMANDER

text 5
COMMANDER WOUNDED...MEDICAL SHIP APPROACHING

text 6
COMMANDER HEALED...RETURNING TO BASE
