text 1
BEACON SIGHTED...PREPARE FOR DROP-OFF COMMANDER

text 2
YOU HAVE SUCCESSFULLY DESTROYED BOTH ELITE GUARD HIVES

text 3
COMMANDER WOUNDED...MEDICAL DROPSHIP SUMMONED

text 4
COMMANDER HEALED...RETURNING TO BASE
