text 1
DROPSHIP BEACON SIGHTED...PREPARE FOR DROP-OFF

text 2
COMMANDER WOUNDED...MEDICAL DROPSHIP APPROACHING

text 3
COMMANDER HEALED...RETURNING TO BASE

text 4
MISSION COMPLETE...GREAT WORK COMMANDER

text 5
WARNING...WARNING...WARNING...BASE DESTROYED
