text 1
DROPSHIP BEACON SIGHTED...PREPARE FOR DROP-OFF

text 2
YOUR BASE HAS BEEN DESTROYED...MISSION ABORTING

text 3
HIGH COUNCIL HIVE DESTROYED...ARTIFACT DISCOVERED

text 4
MAIN HIGH COUNCIL HIVE DETECTED TO THE NORTH-EAST...

text 5
TAKE IT OUT, COMMANDER!

text 6
ALL COUNCIL HIVES DESTROYED...YOU HAVE WON COMMANDER

text 7
YOU HAVE BEEN WOUNDED...PREPARE FOR PICK-UP

text 8
COMMANDER HEALED AND RETURNING TO BASE
