text 1
ALIEN COUNCIL SHIP FOUND...HOLD YOUR POSITION

text 2
BEACON SIGHTED...PREPARE TO LAND COMMANDER

text 3
PERFORMING ALIEN EXTRACTION...

text 4
COMMANDER WOUNDED...MEDICAL DROPSHIP APPROACHING

text 5
COMMANDER HAS BEEN HEALED...RETURNING TO BASE

text 6
THE ALIEN HIVE HAS BEEN DESTROYED...GOOD WORK

text 7
INTERROGATION SUCCESSFUL...BARRIER WILL BE DESTROYED

text 8
DROPPING OFF S.A.R.G.E. BY BARRIER

text 9
EXTRACTION SUCCESSFUL...SUBJECT WILL BE INTERROGATED
