text 1
MARKER 1 Reached

text 2
MARKER 2 Reached

text 3
Enemy AIR DRONES Approaching Base

text 4
Breed An ORTU

text 5
Move Your ORTU WEST To MARKER 1

text 6
Upgrade Your BREEDER POD

text 7
Use Your BROZAAR To Mine P-7

text 8
Select And Deploy XENOWORTS...Hit ENTER To Deploy

text 9
Now Move NORTH-WEST To MARKER 2

text 10
Now Move NORTH-EAST To MARKER 3

text 11
XENOWORTS Only Fire When They Are DEPLOYED

text 12
You Have Completed Your Goals. Be Proud.
