text 1
MIND LINK SUCCESSFUL...PRPARE FOR TELEPORTATION

text 2
YOU HAVE BEEN MORTALLY WOUNDED...PREPARE TO TELEPORT

text 3
RETURNING TO HIVE BROTHER...PREPARE FOR TELEPORTATION

text 4
EXCELLENT WORK BROTHER...YOU HAVE DESTROYED THE HUMANS

text 5
YOUR HIVE HAS BEEN DESTROYED

text 6
BE PROUD...FOR THE PORTALIS IS APPROACHING YOUR HIVE

text 7
NEURAL HIVE MAY NOW BE BUILT, BROTHER

text 8
BROTHER, THE PORTALIS WILL BE GIVEN TO YOU SHORTLY
