text 1
MIND LINK SUCCESSFUL...PRPARE FOR TELEPORTATION

text 4
YOU HAVE BEEN MORTALLY WOUNDED...PREPARE TO TELEPORT

text 5
RETURNING TO HIVE BROTHER...PREPARE FOR TELEPORTATION

text 7
WELL DONE BROTHER...THE HUMAN BASES ARE NO MORE
