text 1
MIND LINK ESTABLISHED...PREPARE FOR TELEPORTATION

text 2
MIND SCAN REVEALS VENT ERUPTION IN THE AREA

text 3
YOU HAVE SUCCEEDED IN YOUR MISSION...BE PROUD

text 4
YOU HAVE BEEN MORTALLY WOUNDED BROTHER...PREPARE TO TELEPORT

text 5
RETURNING TO THE HIVE, BROTHER...PREPARE FOR TELEPORTATION

text 6
YOUR HIVE HAS BEEN DESTROYED
