text 1
YOU HAVE DISCOVERED AN ANCIENT CRYO-CHAMBER

text 2
HOLD YOUR POSITION...PERFORMING MIND PROBE ON DEVICE

text 3
THIS TECHNOLOGY IS LINKED TO OUR SEARCH FOR THE ARTIFACTS

text 4
PROTECT IT USING ANY MEANS NECCESSARY

text 5
BE PROUD...FOR YOU HAVE DONE WELL

text 6
MIND LINK ESTABLISHED...SAUCER APPROACHING

text 7
YOU ARE WOUNDED, BROTHER...PREPARE TO TELEPORT

text 8
RETURNING TO HIVE, BROTHER...PREPARE FOR TELEPORTATION

text 9
YOUR HIVE HAS BEEN DESTROYED, BROTHER
