text 1
SCANNING ARTIFACT DATA...60 SECS LEFT...

text 2
...30 SECONDS LEFT...

text 3
...15 SECONDS LEFT...

text 4
SCANNING COMPLETE...DATA RETRIEVED

text 5
EXIT THROUGH PASSAGE IN NORTH WALL

text 6
MIND LINK ESTABLISHED...PREPARE TO TELEPORT

text 7
...10 SECONDS LEFT...

text 8
...20 SECONDS LEFT...

text 9
...5 SECONDS LEFT...

text 10
...40 SECONDS LEFT...

text 11
...35 SECONDS LEFT...

text 12
...25 SECONDS LEFT...

text 13
...50 SECONDS LEFT...

text 14
YOU HAVE BEEN WOUNDED BROTHER..MISSION ABORTED

text 15
WE SHALL KILL THE HUMANS TOGETHER BROTHER!
