text 1
MIND LINK SUCCESSFUL...PREPARE FOR TELEPORTATION

text 2
MIND SCANS REVEAL GORREM LIFESIGNS IN THE AREA

text 4
YOU HAVE BEEN MORTALLY WOUNDED...PREPARE TO TELEPORT

text 5
RETURNING TO HIVE BROTHER...PREPARE FOR TELEPORTATION

text 6
HUMAN MINING SITE LOCATED

text 7
WELL DONE BROTHER...THE COUNCIL IS PLEASED
