text 1
MIND LINK ESTABLISHED...PREPARE FOR TELEPORTATION

text 2
YOU HAVE BEEN MORTALLY WOUNDED...PREPARE TO TELEPORT

text 3
RETURNING TO BASE, BROTHER...PREPARE FOR TELEPORTATION

text 4
THIS HIVE IS LOST...RETREAT TO THE SOUTHERN HIVE PAD

text 5
WELL DONE, BROTHER...BE PROUD
