text 1
MIND LINK SUCCESSFUL...PRPARE FOR TELEPORTATION

text 2
YOU HAVE BEEN MORTALLY WOUNDED...PREPARE TO TELEPORT

text 3
RETURNING TO HIVE BROTHER...PREPARE FOR TELEPORTATION

text 4
EXCELLENT WORK BROTHER...YOU ARE VICTORIOUS
