text 1
DROPSHIP MIND LINK ESTABLISHED...PREPARE FOR TELEPORTATION

text 2
MORE BROTHERS ARE PROUD TO JOIN YOU

text 3
YOU HAVE FULFILLED OUR DESIRE...BE PROUD

text 4
MIND LINK ESTABLISHED...MORE BROTHERS WILL JOIN YOU

text 5
DO NOT FORGET TO INSPIRE YOUR WARRIORS, BROTHER
