text 1
MIND LINK ESTABLISHED...PREPARE FOR TELEPORTATION

text 2
LEADER WOUNDED...PREPARE TO TELEPORT

text 3
LEADER HEALED...PREPARE FOR TELEPORTATION

text 4
SCIENCE DRONES DESTROYED

text 5
AEROGEN BASES DESTROYED

text 6
DESTROY THE DRONES AND MAKE US PROUD

text 7
YOU HAVE COMPLETED YOUR TASKS BROTHER

text 8
YOUR HIVE HAS BEEN DESTROYED
