text 1
MIND LINK ESTABLISHED...PREPARE FOR TELEPORT

text 2
YOU HAVE ONE DAY CYCLE LEFT, BROTHER

text 3
REMEMBER BROTHER, YOU ONLY HAVE 2 DAY CYCLES

text 4
YOUR HIVE HAS BEEN DESTROYED

text 5
YOU HAVE WON THE WAR, BROTHER. BE PROUD.

text 6
YOU HAVE BEEN WOUNDED. PREPARE TO TELEPORT.

text 7
YOU HAVE BEEN HEALED. RETURING TO HIVE.
