text 1
MAKE YOUR CLAN PROUD, BROTHER

text 2
TRAITOROUS ELITE GUARD ABDUCTION BEGUN

text 3
ABDUCTION SUCCESSFUL...SENDING IN REINFORCEMENTS

text 4
YOU HAVE FAILED...PREPARE FOR TELEPORT

text 5
PROCEED SOUTH. DESTROY THE PROTOTYPE MEDICAL UNITS

text 6
YOU HAVE COMPLETED YOUR MISSION. BE PROUD.
