text 1
MIND LINK ESTABLISHED...PREPARE FOR TELEPORTATION

text 2
LEADER WOUNDED...PREPARE TO TELEPORT

text 3
LEADER HEALED...PREPARE FOR TELEPORTATION

text 4
THE AEROGEN THREAT HERE IS NO MORE, BROTHER

text 5
HIVE DESTROYED...YOU HAVE FAILED, BROTHER
